version: "3.7"

volumes:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    networks:
      - gnet
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=gobot
      - MYSQL_USER=gobot

  gobot_driver:
    image: braidgo/gobot-driver:v0.4.1
    restart: always
    networks:
      - gnet
    depends_on:
      - db
    command: "-no_database=false -httpmock=true -tcpmock=true -script_path scipt/"
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "2"
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=gobot
      - MYSQL_USER=gobot
      - MYSQL_HOST=db


  gobot_editor:
      image: braidgo/gobot-editor:v0.4.1
      restart: always
      depends_on:
        - gobot_driver
      ports:
        - 7777:7777

networks:
  gnet:
    driver: bridge
